let responses = {
    question0: [
        "1st Year",
        "2nd Year",
        "3rd Year",
        "4th Year",
        "Past 4th Year",
        "Masters",
        "PhD",
        "N/A",
    ],
    question1: [
        "Computer Science",
        "Computer Engineering",
        "Information Technology",
        "Management Information Systems",
        "Mechanical Engineering",
        "Electrical Engineering",
        "Physics",
        "IoT",
        "Mathematics",
        "Other",
    ],
    question2: [
        "Software Programming",
        "Program Management",
        "Cyber Security",
        "Artificial Intelligence",
        "Hardware Programming",
        "Robotics",
        "Database Development",
        "Advanced User Support",
        "Networking",
        "UI/UX",
        "Other",
    ],
    question3: [
        "Internship",
        "Full-Time Position",
        "Part-Time Position",
        "Research",
    ],
    question4: [
        "Google",
        "Cisco",
        "Adobe",
        "Facebook",
        "Nike",
        "Uber",
        "Microsoft",
        "NASA",
        "Lyft",
        "Amazon",
        "Twitter",
        "Dell",
        "Apple",
        "Salesforce",
        "Nvidia",
        "Ultimate Software",
        "Intel",
        "LinkedIn",
        "Citrix",
        "IBM",
        "Other",
    ],
    question5: [
        "Industry Internship",
        "Research Experience",
        "Personal Projects",
        "Shadowing Experience",
        "Full-Time Job Experience",
        "Internship/Job Offers",
        "Mentoring student(s)",
        "Being mentored by other student(s)",
        "Being part of a computing group, club, etc",
        "Attending a symposia or other computing events",
        "Attending social events organized by the department",
        "Attending a computing conference",
        "Presenting work to other students (not classwork)",
        "Networking with industry and other professionals",
        "Interacting with students in different year(s)",
        "None",
    ],
    question6: [
        "Peers",
        "Teaching or Learning Assistants",
        "Faculty/Instructors",
        "Online Courses (LinkedIn Learning, LeetCode, Khan Academy, Code.org, etc)",
        "Reading",
        "Videos",
        "Personal Projects",
        "Hackathons",
        "Class Assignments",
        "Class Lectures",
        "Campus workshops by clubs and organizations on campus",
        "Other",
    ],
    question7: [
        "GitHub",
        "LinkedIn",
        "Personal Website",
        "LeetCode Account",
        "HackerRank Account",
        "None of the above",
    ],
    question8: ["0", "1-3", "4-6", "7-9", "10+"],
    question9: ["0", "1-3", "4-6", "7-9", "10+"],
    question17: [
        "American Indian or Alaska Native",
        "Asian",
        "Black or African American",
        "Hispanic, Latinx, or Spanish Origin",
        "Middle Easter or North African",
        "Native Hawaiian or Other Pacific Islander",
        "White",
        "Another race or ethnicity not listed above",
    ],
    question18: ["Female", "Male", "Transgender", "A gender not listed"],
    question19: ["0", "1-5", "6-10", "11-15", "16-20", "21+"],
};

module.exports = responses